name: Publish image to Docker & GHCR

on:
  workflow_dispatch:

jobs:
  build:
    uses: jupiterone/.github/.github/workflows/publish_docker_ghcr.yaml@main
    with:
      package-name: imagepullsecret-patcher
    secrets: inherit
