name: Publish image to Docker & GHCR

on:
  workflow_dispatch:

jobs:
  build:
    uses: jupiterone/.github/.github/workflows/publish_docker_ghcr.yaml@v1.0.1
    with:
      package-name: jupiterone/imagepullsecret-patcher
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
      GHCR_USERNAME: ${{ github.actor }}
      GHCR_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
